version: '3.1'
services:
  api:
    image: emircank/bootcamp:api-v1.0.1
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080-8089:8080"
  ui:
    image: emircank/bootcamp:ui-v1.0.1
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8092:8082"
    environment:
      - API_URL=http://loadbalancer
  loadbalancer:
    image: emircank/bootcamp:loadbalancer-v1.0.1
    build:
      context: ./loadbalancer
      dockerfile: Dockerfile
    ports:
      - "8000:80"